# Generated by Django 4.1.3 on 2024-08-31 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlessboxapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottomlessboxapi.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottomlessboxapi.item')),
            ],
            options={
                'unique_together': {('item', 'category')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(through='bottomlessboxapi.ItemCategory', to='bottomlessboxapi.category'),
        ),
    ]
