# Generated by Django 4.1.3 on 2024-08-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlessboxapi', '0002_remove_item_category_itemcategory_item_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lores', to='bottomlessboxapi.item'),
        ),
    ]
