# Generated by Django 4.1.3 on 2024-09-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlessboxapi', '0003_alter_lore_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
