# Generated by Django 4.1.3 on 2024-09-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlessboxapi', '0004_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='abc', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
