# Generated by Django 4.1.3 on 2024-09-13 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlessboxapi', '0006_item_lore_item_review_alter_lore_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lore',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lore_item', to='bottomlessboxapi.item'),
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_item', to='bottomlessboxapi.item'),
        ),
    ]
