# Generated by Django 4.1.3 on 2024-09-13 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlessboxapi', '0007_alter_lore_item_alter_review_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lore',
        ),
        migrations.RemoveField(
            model_name='item',
            name='review',
        ),
        migrations.AlterField(
            model_name='lore',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bottomlessboxapi.item'),
        ),
    ]
