# Generated by Django 4.1.3 on 2024-09-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottomlessboxapi', '0009_alter_lore_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bottomlessboxapi.item'),
        ),
    ]
